### ISSUE TITLE
[Request] Add OpenUPM support

### ISSUE THREAD

**Issue by MostHated** [stevehalliwell/Nudge#4]
Hey there,
 This looks like a pretty interesting and quite helpful package. Any chance you might be willing to add OpenUPM support? (https://openupm.com/). It makes it easier for folks to create new project initialization scripts and such. That said, after playing around with it a bit, I also wanted to request perhaps a hotkey or two to quickly add the notes to gameobjects, and perhaps another to link multiple objects to one. Keep up the good work, though. I really like the idea. 👍 

Thanks,
-MH

**Comment by stevehalliwell** [comment]
Thanks for the feedback. OpenUPM is definitely going to get some attention in the near future.

Your other two points are on point too, I'm going to make separate issues for them now.

**Comment by stevehalliwell** [comment]
Package now showing correctly in OpenUPM, https://openupm.com/packages/com.aid.nudge/
